# Generates R/code_book-fold-table.R, the frozen table behind the ASCII
# fold of `code_book()` export filenames.
#
# Run from the package root:
#
#   Rscript data-raw/code_book_fold_table.R
#
# WHAT THE TABLE IS. Every code point that the Latin-ASCII transform of
# ICU turns into plain ASCII, with its ASCII replacement. Nothing is
# hand-picked: the scan covers every code point from U+0080 to U+2FFFF
# and keeps what ICU folds. ICU is the oracle here, and only here. The
# package never calls ICU, `iconv()` or a Unicode-aware regular
# expression at run time, so the same title gives the same file name on
# every platform, in every locale, whatever the system libraries.
#
# WHY IT IS FROZEN. A file name is an identifier in someone's pipeline.
# Regenerating this table with a later ICU may change the name an
# existing title maps to, which is a user-visible change: do it on
# purpose, in a release that says so in NEWS.md, never as a side effect.
# tests/testthat/test-code_book_fold_oracle.R compares the frozen table
# with the installed ICU and says so when the two drift apart.
#
# WHAT IS LEFT OUT. The code points that `code_book_ascii_filename()`
# removes before it looks anything up (combining marks and invisible
# format characters, see R/code_book-filename.R) never reach the table,
# so they are not written to it. One of them matters: ICU turns the soft
# hyphen U+00AD into "-", whereas an invisible character has no business
# becoming a visible one in a file name.

stopifnot(requireNamespace("stringi", quietly = TRUE))

icu_version <- stringi::stri_info()$ICU.version
unicode_version <- stringi::stri_info()$Unicode.version

# Keep in step with code_book_is_dropped() in R/code_book-filename.R.
is_dropped <- function(cp) {
  (cp >= 0x0300L & cp <= 0x036FL) |
    (cp >= 0x1AB0L & cp <= 0x1AFFL) |
    (cp >= 0x1DC0L & cp <= 0x1DFFL) |
    (cp >= 0x20D0L & cp <= 0x20FFL) |
    (cp >= 0xFE20L & cp <= 0xFE2FL) |
    cp == 0x00ADL |
    (cp >= 0x200BL & cp <= 0x200FL) |
    (cp >= 0x202AL & cp <= 0x202EL) |
    (cp >= 0x2060L & cp <= 0x206FL) |
    (cp >= 0xFE00L & cp <= 0xFE0FL) |
    cp == 0xFEFFL
}

cp <- setdiff(0x80:0x2FFFF, 0xD800:0xDFFF)
ch <- intToUtf8(cp, multiple = TRUE)
to <- stringi::stri_trans_general(ch, "Latin-ASCII")

is_ascii <- !grepl("[^\\x01-\\x7F]", to, perl = TRUE)
keep <- is_ascii & nzchar(to) & to != ch & !is_dropped(cp)
fold <- data.frame(cp = cp[keep], to = to[keep], stringsAsFactors = FALSE)
# Radix order compares bytes: the file comes out the same on every
# machine, whatever the collation of the session that regenerates it.
fold <- fold[order(fold$to, fold$cp, method = "radix"), ]

# One element per ASCII target, at most `per_line` code points each, so
# a target with many sources spans several elements of the same name.
per_line <- 10L
entries <- character()
for (target in unique(fold$to)) {
  hex <- sprintf("%04X", fold$cp[fold$to == target])
  chunks <- split(hex, ceiling(seq_along(hex) / per_line))
  for (chunk in chunks) {
    entries <- c(
      entries,
      sprintf(
        "  %s = \"%s\"",
        encodeString(target, quote = "\""),
        paste(chunk, collapse = " ")
      )
    )
  }
}

header <- c(
  "# Generated by data-raw/code_book_fold_table.R -- do not edit by hand.",
  "#",
  "# The ASCII fold of `code_book()` export filenames: every code point that",
  sprintf(
    "# the Latin-ASCII transform of ICU %s (Unicode %s) turns into plain ASCII,",
    icu_version, unicode_version
  ),
  sprintf(
    "# %d code points in all. FROZEN: a file name is an identifier in a user's",
    nrow(fold)
  ),
  "# pipeline, so regenerating the table is a user-visible change that belongs",
  "# in a release and in NEWS.md. See the generator for the full rationale.",
  "#",
  "# Each element reads `\"<ASCII replacement>\" = \"<code points, hexadecimal>\"`.",
  "# A replacement with many sources spans several elements of the same name.",
  "code_book_fold_table <- c("
)

footer <- c(
  ")",
  "",
  "# The two parallel vectors the fold looks up, built once when the package",
  "# is installed: code points, and the replacement of each.",
  "code_book_fold_from <- strtoi(",
  "  unlist(strsplit(code_book_fold_table, \" \", fixed = TRUE), use.names = FALSE),",
  "  base = 16L",
  ")",
  "code_book_fold_to <- rep(",
  "  names(code_book_fold_table),",
  "  lengths(strsplit(code_book_fold_table, \" \", fixed = TRUE))",
  ")"
)

body <- paste0(entries, c(rep(",", length(entries) - 1L), ""))
out <- c(header, body, footer)

stopifnot(!any(grepl("[^\\x01-\\x7F]", out, perl = TRUE)))
con <- file("R/code_book-fold-table.R", open = "wb")
writeLines(out, con, sep = "\n")
close(con)

cat(sprintf(
  "R/code_book-fold-table.R written: %d code points, %d replacements, %d lines (ICU %s, Unicode %s).\n",
  nrow(fold), length(unique(fold$to)), length(out), icu_version, unicode_version
))
