# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# This workflow runs R CMD check on multiple OS / R versions
# and is safe for CRAN submissions (no system dependencies like qpdf or gs)

on:
  workflow_dispatch:     # ✅ allows manual run from GitHub
  push:
    branches: [main, master]
    paths:
      - "R/**"
      - "tests/**"
      - "man/**"
      - "DESCRIPTION"
      - "NAMESPACE"
      - ".github/workflows/R-CMD-check.yaml"
  pull_request:
    branches: [main, master]

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      CI: true   # used by skip_on_ci() in tests

    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v4

      # 2️⃣ Set up R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # 3️⃣ Install package dependencies from DESCRIPTION
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      # 4️⃣ Run R CMD check (without system dependencies like qpdf)
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: false
          args: --no-manual --as-cran
          build_args: --no-manual

      # 5️⃣ Upload R CMD check results if a failure occurs
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-check-results
          path: check
